Rails.application.config.assets.precompile += %w( font-awesome.min.css )
Rails.application.config.assets.precompile += %w( table-sorter-style.css )

Rails.application.config.assets.precompile += %w( jquery.min.js )
Rails.application.config.assets.precompile += %w( jquery.tablesorter.js )
Rails.application.config.assets.precompile += %w( google_analytics.js )
Rails.application.config.assets.precompile += %w( bootstrap.min.js )
Rails.application.config.assets.precompile += %w( map_of_venues.js )
Rails.application.config.assets.precompile += %w( map_of_accommodations.js )
Rails.application.config.assets.precompile += %w( rsvp.js )
Rails.application.config.assets.precompile += %w( home.js )
Rails.application.config.assets.precompile += %w( photos.js )

Rails.application.config.assets.precompile += %w( MonsieurLaDoulaise-Regular.ttf )
Rails.application.config.assets.precompile += %w( GreatVibes-Regular.ttf )
Rails.application.config.assets.precompile += %w( PoiretOne-Regular.ttf )
Rails.application.config.assets.precompile += %w( DancingScript-Regular.ttf )
Rails.application.config.assets.precompile += %w( DancingScript-Bold.ttf )
Rails.application.config.assets.precompile += %w( glyphicons-halflings-regular.eot )
Rails.application.config.assets.precompile += %w( glyphicons-halflings-regular.svg )
Rails.application.config.assets.precompile += %w( glyphicons-halflings-regular.ttf )
Rails.application.config.assets.precompile += %w( glyphicons-halflings-regular.woff )
