Rails.application.config.assets.precompile += %w( bootstrap.min.css, bootstrap-theme.min.css, bootstrap-theme.css.map )
Rails.application.config.assets.precompile += %w( font-awesome.min.css, font-awesome.css )
Rails.application.config.assets.precompile += %w( jquery.js )
Rails.application.config.assets.precompile += %w( bootstrap.min.js )
Rails.application.config.assets.precompile += %w( MonsieurLaDoulaise-Regular.ttf )
Rails.application.config.assets.precompile += %w( GreatVibes-Regular.ttf )
Rails.application.config.assets.precompile += %w( PoiretOne-Regular.ttf )