# Enter your per-environment constants below

development: &default
  constant1:  "value1"
  constant2:  "value2"
  skyscanner_widget_key: '77c9d87a-07a4-47dd-b8a8-aa8336686af9'

production:
  <<: *default
  
test:
  <<: *default
