# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b9193673c31e6b5c4740da2c996cd36a7a6b1a1a1833ac23d552dac0b46175492f2ab1cc63353a4d603cbb442b092da661402d87d1b4c46cfe7088929518444

test:
  secret_key_base: 367dfe350381f43cbe7babb4ca5ca4b6756bde62a259b912c48d28121bb2e5c975a292efa0fc409bdbc6fc2155dec0a867e9772ed204aac202374bb04fd14267

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
